---
# SmallStep CA ClusterIssuer (for internal *.homelab.local certificates)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: smallstep-ca
spec:
  acme:
    # SmallStep Cloud ACME endpoint
    server: https://pki.mylaniakea.ca.smallstep.com/acme/pki-mylaniakea-acme/directory
    # Email for ACME (can be anything for SmallStep)
    email: admin@homelab.local
    # Private key secret
    privateKeySecretRef:
      name: smallstep-acme-key
    # ACME provisioner (need to confirm name from your SmallStep instance)
    # Usually "acme" or can check at: https://pki.mylaniakea.ca.smallstep.com/provisioners
    # For now using standard ACME path
    solvers:
    - http01:
        ingress:
          class: traefik

---
# Let's Encrypt ClusterIssuer via Cloudflare DNS-01 (for public domains)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email for Let's Encrypt notifications
    email: matthew@mylaniakea.com
    # Private key for ACME account
    privateKeySecretRef:
      name: letsencrypt-acme-key
    # Cloudflare DNS-01 challenge
    solvers:
    - dns01:
        cloudflare:
          email: matthew@mylaniakea.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token

---
# Certificate for internal domains (SmallStep)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-local-cert
  namespace: homelab
spec:
  secretName: homelab-local-tls
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  commonName: "*.homelab.local"
  dnsNames:
  - "*.homelab.local"
  - "homelab.local"
  issuerRef:
    name: smallstep-ca
    kind: ClusterIssuer

---
# Certificate for mylaniakea.com (Let's Encrypt)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mylaniakea-com-cert
  namespace: homelab
spec:
  secretName: mylaniakea-com-tls
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  commonName: "mylaniakea.com"
  dnsNames:
  - "mylaniakea.com"
  - "*.mylaniakea.com"
  - "unity.mylaniakea.com"
  - "ui.mylaniakea.com"
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer

---
# Certificate for holons.dev (Let's Encrypt)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: holons-dev-cert
  namespace: homelab
spec:
  secretName: holons-dev-tls
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  commonName: "holons.dev"
  dnsNames:
  - "holons.dev"
  - "*.holons.dev"
  - "unity.holons.dev"
  - "ui.holons.dev"
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
