ALTER TABLE settings ADD COLUMN IF NOT EXISTS polling_interval INTEGER DEFAULT 30;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS alert_sound_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS maintenance_mode_until TIMESTAMP WITH TIME ZONE;
