"""add docker hosts table

Revision ID: add_docker_hosts_001
Revises: tenant_support_001
Create Date: 2026-01-08 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_docker_hosts_001'
down_revision = 'tenant_support_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docker_hosts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('host_url', sa.String(length=500), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
        sa.Column('health_status', sa.String(length=50), nullable=True),
        sa.Column('health_message', sa.Text(), nullable=True),
        sa.Column('container_count', sa.Integer(), nullable=True),
        sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docker_hosts_id'), 'docker_hosts', ['id'], unique=False)
    op.create_index(op.f('ix_docker_hosts_is_active'), 'docker_hosts', ['is_active'], unique=False)
    op.create_index(op.f('ix_docker_hosts_name'), 'docker_hosts', ['name'], unique=True)
    op.create_index(op.f('ix_docker_hosts_tenant_id'), 'docker_hosts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docker_hosts_tenant_id'), table_name='docker_hosts')
    op.drop_index(op.f('ix_docker_hosts_name'), table_name='docker_hosts')
    op.drop_index(op.f('ix_docker_hosts_is_active'), table_name='docker_hosts')
    op.drop_index(op.f('ix_docker_hosts_id'), table_name='docker_hosts')
    op.drop_table('docker_hosts')
    # ### end Alembic commands ###
